config/routes.rb
Rails.application.routes.draw do

    # youtube_filter namespace
    namespace :youtube_filter do

        # root
        root 'youtube_filter/subtitles#index'

        # resources
        resources :categories
        resources :subtitles

    end

    # static pages
    get 'pages/results'

end

app/models/subtitle.rb
class Subtitle < ApplicationRecord

  # belongs to
  belongs_to :category

  # has many
  has_many :predicate_group_results, dependent: :destroy
  has_many :submodalities_group_results, dependent: :destroy
  has_many :word_group_results, dependent: :destroy
  has_many :theme_group_results, dependent: :destroy

  def self.syllable_count
    pluck(:syllable).sum
  end

end

app/controllers/subtitles_controller.rb
class SubtitlesController < ApplicationController
  before_action :set_subtitle, only: [:edit, :update, :destroy]

    # GET /subtitles
    # GET /subtitles.json
    def index
        @titles = Subtitle.group(:title)
    end

    # GET /subtitles/1
    # GET /subtitles/1.json
    def show
        @subtitles = category_subtitles.paginate(page: params[:page], per_page: 12).order('counter DESC')
        @wordgroups = category_filter(WordGroupResult).where(title: category_title)
        @filters = category_filter(FilterGroupResult).where(title: category_title)
    end

    # GET /subtitles/new
    def new
        @subtitle = Subtitle.new
    end

    # GET /subtitles/1/edit
    def edit
    end

    # POST /subtitles
    def create
        @subtitle = Subtitle.new(subtitle_params)

        respond_to do |format|
            if @subtitle.save
                format.html { redirect_to @subtitle, notice: 'Subtitle was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    # PATCH/PUT /subtitles/1
    def update
        respond_to do |format|
            if @subtitle.update(subtitle_params)
                format.html { redirect_to @subtitle, notice: 'Subtitle was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end

    # DELETE /subtitles/1
    def destroy
        @subtitle.destroy
        respond_to do |format|
            format.html { redirect_to subtitles_url, notice: 'Subtitle was successfully destroyed.' }
        end
    end

  private

    def category_filter(model)
        Subtitle.where(id: model.pluck(:subtitle_id)).order('counter DESC').paginate(page: params[:page], per_page: 12)
    end

    def category_title
        @title = Subtitle.find(params[:id]).title
    end

    # find all categorys matching id
    def category_subtitles
        subtitle  = Subtitle.where(category_id: params[:category], title: category_title)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subtitle
      @subtitle = Subtitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtitle_params
      params.require(:subtitle).permit(:word, :title, :counter)
    end
end

app/controllers/youtube_filter/subtitles_controller.rb
class YoutubeFilter::SubtitlesController < ApplicationController
  before_action :set_subtitle, only: [:edit, :update, :destroy]

    # GET /subtitles
    def index
        @titles = Subtitle.group(:title)
    end

    # GET /subtitles/1
    def show
      @sub = Subtitle.all.order('length DESC')
        @subtitles = category_subtitles.paginate(page: params[:page], per_page: 12).order('word_rank DESC')
        @wordgroups = category_filter(WordGroupResult).where(title: category_title).where("length > 4")
        @themes = category_filter(ThemeGroupResult).where(title: category_title)
        @predicates = category_filter(PredicateGroupResult).where(title: category_title)
        @submodalities = category_filter(SubmodalitiesGroupResult).where(title: category_title)
    end


  private


    def category_filter(model)
        Subtitle.where(id: model.pluck(:subtitle_id)).order('counter DESC').paginate(page: params[:page], per_page: 12)
    end

    def category_title
        @title = Subtitle.find(params[:id]).title
    end

    # find all categorys matching id
    def category_subtitles
        subtitle  = Subtitle.where(category_id: params[:category], title: category_title)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subtitle
      @subtitle = Subtitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtitle_params
      params.require(:subtitle).permit(:word, :title, :counter)
    end
end

app/helpers/subtitles_helper.rb
module SubtitlesHelper
end

app/views/subtitles/edit.html.erb
<h1>Editing Subtitle</h1>

<%= render 'form', subtitle: @subtitle %>

<%= link_to 'Show', @subtitle %> |
<%= link_to 'Back', subtitles_path %>

app/views/subtitles/index.html.erb
<% title controller_name + " " + action_name %>
<header class="subtitle-index-header">
  <h1>Listing Subtitles</h1>
</header>

<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |subtitle| %>
        <tr> 
            <td><%= link_to subtitle.title, subtitle_path(subtitle) %></td> 
        </tr>
    <% end %>
  <tbody>


</table>

<br>

app/views/subtitles/new.html.erb
<h1>New Subtitle</h1>

<%= render 'form', subtitle: @subtitle %>

<%= link_to 'Back', subtitles_path %>

app/views/subtitles/show.html.erb
<%= render "subtitles/partials/aside" %>

<main class="small">
    <!--begin category subtitles-->
      <% if params[:category] == "1" %>
        <tbody>
          <%= render "subtitles/partials/subtitle" %>
        </tbody>

      <!--begin category filter-->
      <% elsif params[:category] == "2" %>
        <tbody>
          <%= render "subtitles/partials/filter" %>
        </tbody>

      <!--begin category wordgroup-->
      <% elsif params[:category] == "3" %>
        <tbody>
          <%= render "subtitles/partials/wordgroup" %>
        </tbody>

      <% end %>
</main>